import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, ActivityIndicator, TextInput } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useTheme } from '../../contexts/ThemeContext';
import { generateSampleOrders, deleteSampleData, resetAllOrders, resetStaffUsersAndPasswords } from '../../services/firestoreSeed';
import { appConfig } from '../../config/appConfig';
import { hashPassword } from '../../utils/passwordHash';
import { alertService } from '../../services/alertService';
import Icon from '../../components/ui/Icon';
import AnimatedButton from '../../components/ui/AnimatedButton';

// Helper function to convert hex color to rgba with opacity
const hexToRgba = (hex, opacity) => {
  // Remove # if present
  const cleanHex = hex.replace('#', '');
  // Parse RGB values
  const r = parseInt(cleanHex.substring(0, 2), 16);
  const g = parseInt(cleanHex.substring(2, 4), 16);
  const b = parseInt(cleanHex.substring(4, 6), 16);
  // Return rgba string
  return `rgba(${r}, ${g}, ${b}, ${opacity})`;
};

const SeedDatabaseScreen = () => {
  const navigation = useNavigation();
  const insets = useSafeAreaInsets();
  const { theme, spacing, borderRadius, typography } = useTheme();
  const [generating, setGenerating] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [resettingOrders, setResettingOrders] = useState(false);
  const [resetting, setResetting] = useState(false);
  const [result, setResult] = useState(null);
  const [passwordInput, setPasswordInput] = useState('');
  const [generatedHash, setGeneratedHash] = useState('');

  const handleGenerateSamples = async () => {
    if (appConfig.USE_MOCKS) {
      alertService.warning(
        'Mock Mode Enabled',
        'Cannot generate data samples when USE_MOCKS is true.\n\nPlease set EXPO_PUBLIC_USE_MOCKS=false in your .env file and restart the app.'
      );
      return;
    }

    alertService.alert(
      'Generate Sample Orders',
      'This will generate sample orders for data visualization:\n\n' +
      '• 25 Sample Orders\n' +
      '• Various statuses (pending, preparing, ready, completed, cancelled)\n' +
      '• Mix of dine-in and take-out orders\n' +
      '• Mix of cash and GCash payments\n\n' +
      'All sample orders will be marked and can be deleted later.\n' +
      'Real orders will NOT be affected.\n\n' +
      'Continue?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Generate',
          style: 'default',
          onPress: async () => {
            setGenerating(true);
            setResult(null);
            try {
              const result = await generateSampleOrders();
              setResult({ success: true, message: `Generated ${result.generatedOrders} sample orders successfully!` });
              alertService.success('Success', `Generated ${result.generatedOrders} sample orders successfully!`);
            } catch (error) {
              setResult({ success: false, message: error.message || 'Failed to generate sample orders' });
              alertService.error('Error', error.message || 'Failed to generate sample orders. Check your Firebase configuration.');
            } finally {
              setGenerating(false);
            }
          }
        }
      ]
    );
  };

  const handleDeleteSamples = async () => {
    if (appConfig.USE_MOCKS) {
      alertService.warning(
        'Mock Mode Enabled',
        'Cannot delete data samples when USE_MOCKS is true.\n\nPlease set EXPO_PUBLIC_USE_MOCKS=false in your .env file and restart the app.'
      );
      return;
    }

    alertService.alert(
      'Delete Sample Orders',
      'This will DELETE ONLY sample orders (marked with isSample: true):\n\n' +
      '• Sample orders generated by "Generate Sample Orders"\n' +
      '• Test/Demo discounts (if any)\n\n' +
      '✅ Real user-inputted orders will be PRESERVED\n\n' +
      '⚠️  This action CANNOT be undone!\n\n' +
      'Are you sure you want to continue?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete Samples',
          style: 'destructive',
          onPress: async () => {
            setDeleting(true);
            setResult(null);
            try {
              const deleteResult = await deleteSampleData();
              setResult({ 
                success: true, 
                message: `Sample data deleted successfully!\n\nDeleted: ${deleteResult.deletedOrders} sample orders\nPreserved: ${deleteResult.preservedOrders || 0} real orders\nDeleted: ${deleteResult.deletedDiscounts} test discounts.` 
              });
              alertService.success(
                'Success', 
                `Sample data deleted successfully!\n\nDeleted ${deleteResult.deletedOrders} sample orders.\nPreserved ${deleteResult.preservedOrders || 0} real orders.\nDeleted ${deleteResult.deletedDiscounts} test discounts.`
              );
            } catch (error) {
              setResult({ success: false, message: error.message || 'Failed to delete sample data' });
              alertService.error('Error', error.message || 'Failed to delete sample data. Check your Firebase configuration.');
            } finally {
              setDeleting(false);
            }
          }
        }
      ]
    );
  };

  const handleResetAllOrders = async () => {
    if (appConfig.USE_MOCKS) {
      alertService.warning(
        'Mock Mode Enabled',
        'Cannot reset orders when USE_MOCKS is true.\n\nPlease set EXPO_PUBLIC_USE_MOCKS=false in your .env file and restart the app.'
      );
      return;
    }

    alertService.alert(
      'Reset All Orders',
      '⚠️  WARNING: This will DELETE ALL ORDERS!\n\n' +
      '• All sample orders\n' +
      '• All real user-inputted orders\n' +
      '• Everything in the orders collection\n\n' +
      'This action CANNOT be undone!\n\n' +
      'Use this to prevent database overflow.\n\n' +
      'Are you absolutely sure?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Reset All',
          style: 'destructive',
          onPress: async () => {
            setResettingOrders(true);
            setResult(null);
            try {
              const resetResult = await resetAllOrders();
              setResult({ 
                success: true, 
                message: `All orders reset successfully!\n\nDeleted: ${resetResult.deletedOrders} orders.\n\nDatabase has been cleared to prevent overflow.` 
              });
              alertService.success(
                'Success', 
                `All orders reset successfully!\n\nDeleted ${resetResult.deletedOrders} orders.\n\nDatabase has been cleared to prevent overflow.`
              );
            } catch (error) {
              setResult({ success: false, message: error.message || 'Failed to reset orders' });
              alertService.error('Error', error.message || 'Failed to reset orders. Check your Firebase configuration.');
            } finally {
              setResettingOrders(false);
            }
          }
        }
      ]
    );
  };

  const handleResetStaff = async () => {
    if (appConfig.USE_MOCKS) {
      alertService.warning(
        'Mock Mode Enabled',
        'Cannot reset staff users when USE_MOCKS is true.\n\nPlease set EXPO_PUBLIC_USE_MOCKS=false in your .env file and restart the app.'
      );
      return;
    }

    alertService.alert(
      'Reset Staff Users & Passwords',
      'This will:\n\n' +
      '• DELETE all existing staff users (admin, cashier, kitchen, developer)\n' +
      '• CREATE a new admin user\n' +
      '• RESET the payment confirmation password\n\n' +
      '⚠️  Default Credentials:\n' +
      '   Username: admin\n' +
      '   Password: admin123\n' +
      '   Payment Password: admin123\n\n' +
      '⚠️  IMPORTANT: Change these passwords immediately after first login!\n\n' +
      'This action CANNOT be undone!\n\n' +
      'Are you sure you want to continue?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Reset',
          style: 'destructive',
          onPress: async () => {
            setResetting(true);
            setResult(null);
            try {
              const resetResult = await resetStaffUsersAndPasswords();
              const message = `Staff users and passwords reset successfully!\n\n` +
                `✅ Deleted ${resetResult.deletedUsers} staff users\n` +
                `✅ Created new admin user: ${resetResult.newAdminUsername}\n` +
                `✅ Reset payment password\n\n` +
                `🔑 Default Credentials:\n` +
                `   Username: ${resetResult.newAdminUsername}\n` +
                `   Password: ${resetResult.defaultPassword}\n` +
                `   Payment Password: ${resetResult.defaultPaymentPassword}\n\n` +
                `⚠️  Change these passwords immediately!`;
              setResult({ 
                success: true, 
                message: message
              });
              alertService.success(
                'Success', 
                message
              );
            } catch (error) {
              setResult({ success: false, message: error.message || 'Failed to reset staff users and passwords' });
              alertService.error('Error', error.message || 'Failed to reset staff users and passwords. Check your Firebase configuration.');
            } finally {
              setResetting(false);
            }
          }
        }
      ]
    );
  };

  const handleGenerateHash = () => {
    if (!passwordInput.trim()) {
      alertService.warning('Input Required', 'Please enter a password to generate hash.');
      return;
    }
    const hash = hashPassword(passwordInput.trim());
    setGeneratedHash(hash);
    alertService.success('Hash Generated', `Password hash generated!\n\nCopy this hash and paste it into Firestore for the user's password field.`);
  };


  return (
    <View style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <View style={[
        styles.header,
        {
          backgroundColor: theme.colors.surface,
          borderBottomColor: theme.colors.border,
          paddingTop: insets.top + spacing.lg,
          paddingHorizontal: spacing.md,
          paddingBottom: spacing.md,
        }
      ]}>
        <View style={styles.headerContent}>
          <View style={styles.titleRow}>
            <AnimatedButton
              onPress={() => navigation.goBack()}
              style={{
                backgroundColor: 'transparent',
                marginRight: spacing.sm,
              }}
            >
              <View
                style={{
                  backgroundColor: hexToRgba(theme.colors.error, 0.1),
                  borderWidth: 1.5,
                  borderColor: theme.colors.error + '40',
                  padding: spacing.sm,
                  borderRadius: 999,
                  justifyContent: 'center',
                  alignItems: 'center',
                  shadowColor: theme.colors.error,
                  shadowOffset: { width: 0, height: 1 },
                  shadowOpacity: 0.1,
                  shadowRadius: 2,
                  elevation: 1,
                }}
              >
                <Icon
                  name="arrow-back"
                  library="ionicons"
                  size={22}
                  color={theme.colors.error}
                  responsive={true}
                  hitArea={false}
                  style={{ margin: 0 }}
                />
              </View>
            </AnimatedButton>
            <Icon
              name="layers"
              library="ionicons"
              size={28}
              color={theme.colors.primary}
              style={{ marginRight: spacing.sm }}
            />
            <View>
              <Text style={[
                styles.title,
                {
                  color: theme.colors.text,
                  ...typography.h2,
                  marginBottom: spacing.xs,
                }
              ]}>
                Data Samples
              </Text>
              <Text style={[
                styles.subtitle,
                {
                  color: theme.colors.textSecondary,
                  ...typography.caption,
                }
              ]}>
                Generate or delete sample data
              </Text>
            </View>
          </View>
        </View>
      </View>

      <ScrollView contentContainerStyle={[
        styles.content,
        {
          padding: spacing.md,
          paddingBottom: spacing.xxl,
        }
      ]}>
        <View style={[
          styles.infoCard,
          {
            backgroundColor: theme.colors.surface,
            borderColor: theme.colors.border,
            borderRadius: borderRadius.xl,
            padding: spacing.lg,
            marginBottom: spacing.md,
            borderWidth: 1,
          }
        ]}>
          <Icon
            name="information-circle"
            library="ionicons"
            size={24}
            color={theme.colors.info}
            style={{ marginBottom: spacing.sm }}
          />
          <Text style={[
            styles.infoTitle,
            {
              color: theme.colors.text,
              ...typography.h4,
              marginBottom: spacing.sm,
            }
          ]}>
            What gets generated?
          </Text>
          <Text style={[
            styles.infoText,
            {
              color: theme.colors.textSecondary,
              ...typography.body,
              marginBottom: spacing.xs,
            }
          ]}>
            • 25 Sample Orders
          </Text>
          <Text style={[
            styles.infoText,
            {
              color: theme.colors.textSecondary,
              ...typography.body,
              marginBottom: spacing.xs,
            }
          ]}>
            • Various statuses (pending, preparing, ready, completed, cancelled)
          </Text>
          <Text style={[
            styles.infoText,
            {
              color: theme.colors.textSecondary,
              ...typography.body,
              marginBottom: spacing.xs,
            }
          ]}>
            • Mix of dine-in and take-out orders
          </Text>
          <Text style={[
            styles.infoText,
            {
              color: theme.colors.textSecondary,
              ...typography.body,
            }
          ]}>
            • Mix of cash and GCash payments
          </Text>
        </View>

        {appConfig.USE_MOCKS && (
          <View style={[
            styles.warningCard,
            {
              backgroundColor: theme.colors.warningLight + '30',
              borderColor: theme.colors.warning,
              borderRadius: borderRadius.xl,
              padding: spacing.lg,
              marginBottom: spacing.md,
              borderWidth: 1.5,
            }
          ]}>
            <Icon
              name="warning"
              library="ionicons"
              size={24}
              color={theme.colors.warning}
              style={{ marginBottom: spacing.sm }}
            />
            <Text style={[
              styles.warningTitle,
              {
                color: theme.colors.warning,
                ...typography.h4,
                marginBottom: spacing.sm,
              }
            ]}>
              Mock Mode Enabled
            </Text>
            <Text style={[
              styles.warningText,
              {
                color: theme.colors.text,
                ...typography.body,
              }
            ]}>
              Cannot seed Firestore when USE_MOCKS is true.{'\n\n'}
              Set EXPO_PUBLIC_USE_MOCKS=false in your .env file and restart the app.
            </Text>
          </View>
        )}

        {result && (
          <View style={[
            styles.resultCard,
            {
              backgroundColor: result.success 
                ? theme.colors.successLight + '30' 
                : theme.colors.errorLight + '30',
              borderColor: result.success 
                ? theme.colors.success 
                : theme.colors.error,
              borderRadius: borderRadius.xl,
              padding: spacing.lg,
              marginBottom: spacing.md,
              borderWidth: 1.5,
            }
          ]}>
            <Icon
              name={result.success ? 'checkmark-circle' : 'close-circle'}
              library="ionicons"
              size={24}
              color={result.success ? theme.colors.success : theme.colors.error}
              style={{ marginBottom: spacing.sm }}
            />
            <Text style={[
              styles.resultText,
              {
                color: result.success ? theme.colors.success : theme.colors.error,
                ...typography.body,
              }
            ]}>
              {result.message}
            </Text>
          </View>
        )}

        <AnimatedButton
          style={[
            styles.seedButton,
            {
              backgroundColor: appConfig.USE_MOCKS 
                ? theme.colors.surfaceVariant 
                : theme.colors.primary,
              borderRadius: borderRadius.lg,
              paddingVertical: spacing.lg,
              shadowColor: theme.colors.primary,
              marginBottom: spacing.md,
            }
          ]}
          onPress={handleGenerateSamples}
          disabled={generating || appConfig.USE_MOCKS}
        >
          {generating ? (
            <ActivityIndicator color={theme.colors.onPrimary} />
          ) : (
            <>
              <Icon
                name="add-circle"
                library="ionicons"
                size={24}
                color={appConfig.USE_MOCKS ? theme.colors.textSecondary : theme.colors.onPrimary}
                style={{ marginRight: spacing.sm }}
              />
              <Text style={[
                styles.seedButtonText,
                {
                  color: appConfig.USE_MOCKS 
                    ? theme.colors.textSecondary 
                    : theme.colors.onPrimary,
                  ...typography.button,
                }
              ]}>
                Generate Sample Orders
              </Text>
            </>
          )}
        </AnimatedButton>

        <AnimatedButton
          style={[
            styles.seedButton,
            {
              backgroundColor: appConfig.USE_MOCKS 
                ? theme.colors.surfaceVariant 
                : theme.colors.error,
              borderRadius: borderRadius.lg,
              paddingVertical: spacing.lg,
              shadowColor: theme.colors.error,
              marginBottom: spacing.md,
            }
          ]}
          onPress={handleDeleteSamples}
          disabled={deleting || appConfig.USE_MOCKS}
        >
          {deleting ? (
            <ActivityIndicator color={theme.colors.onError || '#FFFFFF'} />
          ) : (
            <>
              <Icon
                name="trash"
                library="ionicons"
                size={24}
                color={appConfig.USE_MOCKS ? theme.colors.textSecondary : (theme.colors.onError || '#FFFFFF')}
                style={{ marginRight: spacing.sm }}
              />
              <Text style={[
                styles.seedButtonText,
                {
                  color: appConfig.USE_MOCKS 
                    ? theme.colors.textSecondary 
                    : (theme.colors.onError || '#FFFFFF'),
                  ...typography.button,
                }
              ]}>
                Delete Sample Orders
              </Text>
            </>
          )}
        </AnimatedButton>

        <AnimatedButton
          style={[
            styles.seedButton,
            {
              backgroundColor: appConfig.USE_MOCKS 
                ? theme.colors.surfaceVariant 
                : '#DC2626', // Red color for destructive action
              borderRadius: borderRadius.lg,
              paddingVertical: spacing.lg,
              shadowColor: '#DC2626',
              marginBottom: spacing.md,
            }
          ]}
          onPress={handleResetAllOrders}
          disabled={resettingOrders || appConfig.USE_MOCKS}
        >
          {resettingOrders ? (
            <ActivityIndicator color="#FFFFFF" />
          ) : (
            <>
              <Icon
                name="trash-bin"
                library="ionicons"
                size={24}
                color={appConfig.USE_MOCKS ? theme.colors.textSecondary : '#FFFFFF'}
                style={{ marginRight: spacing.sm }}
              />
              <Text style={[
                styles.seedButtonText,
                {
                  color: appConfig.USE_MOCKS 
                    ? theme.colors.textSecondary 
                    : '#FFFFFF',
                  ...typography.button,
                }
              ]}>
                Reset All Orders (Delete Everything)
              </Text>
            </>
          )}
        </AnimatedButton>

        <AnimatedButton
          style={[
            styles.seedButton,
            {
              backgroundColor: appConfig.USE_MOCKS 
                ? theme.colors.surfaceVariant 
                : theme.colors.warning,
              borderRadius: borderRadius.lg,
              paddingVertical: spacing.lg,
              shadowColor: theme.colors.warning,
              marginBottom: spacing.md,
            }
          ]}
          onPress={handleResetStaff}
          disabled={resetting || appConfig.USE_MOCKS}
        >
          {resetting ? (
            <ActivityIndicator color={theme.colors.onWarning || '#FFFFFF'} />
          ) : (
            <>
              <Icon
                name="key"
                library="ionicons"
                size={24}
                color={appConfig.USE_MOCKS ? theme.colors.textSecondary : (theme.colors.onWarning || '#FFFFFF')}
                style={{ marginRight: spacing.sm }}
              />
              <Text style={[
                styles.seedButtonText,
                {
                  color: appConfig.USE_MOCKS 
                    ? theme.colors.textSecondary 
                    : (theme.colors.onWarning || '#FFFFFF'),
                  ...typography.button,
                }
              ]}>
                Reset Staff Users & Passwords
              </Text>
            </>
          )}
        </AnimatedButton>


        {/* Password Hash Generator */}
        <View style={[
          styles.infoCard,
          {
            backgroundColor: theme.colors.surface,
            borderColor: theme.colors.border,
            borderRadius: borderRadius.xl,
            padding: spacing.lg,
            marginTop: spacing.md,
            borderWidth: 1,
          }
        ]}>
          <Icon
            name="key"
            library="ionicons"
            size={24}
            color={theme.colors.primary}
            style={{ marginBottom: spacing.sm }}
          />
          <Text style={[
            styles.infoTitle,
            {
              color: theme.colors.text,
              ...typography.h4,
              marginBottom: spacing.sm,
            }
          ]}>
            Password Hash Generator
          </Text>
          <Text style={[
            styles.infoText,
            {
              color: theme.colors.textSecondary,
              ...typography.caption,
              marginBottom: spacing.md,
            }
          ]}>
            Generate a password hash to manually update user passwords in Firestore.
          </Text>
          
          <TextInput
            style={[
              {
                backgroundColor: theme.colors.background,
                borderColor: theme.colors.border,
                color: theme.colors.text,
                borderRadius: borderRadius.md,
                borderWidth: 1,
                padding: spacing.sm,
                marginBottom: spacing.sm,
                ...typography.body,
              }
            ]}
            placeholder="Enter password"
            placeholderTextColor={theme.colors.textSecondary}
            value={passwordInput}
            onChangeText={setPasswordInput}
            secureTextEntry
          />

          <AnimatedButton
            style={[
              {
                backgroundColor: theme.colors.primary,
                borderRadius: borderRadius.md,
                paddingVertical: spacing.sm,
                marginBottom: spacing.sm,
              }
            ]}
            onPress={handleGenerateHash}
          >
            <Text style={[
              {
                color: theme.colors.onPrimary,
                ...typography.button,
              }
            ]}>
              Generate Hash
            </Text>
          </AnimatedButton>

          {generatedHash && (
            <View style={[
              {
                backgroundColor: theme.colors.primaryContainer,
                borderRadius: borderRadius.md,
                padding: spacing.sm,
                marginTop: spacing.sm,
              }
            ]}>
              <Text style={[
                {
                  color: theme.colors.primary,
                  ...typography.caption,
                  marginBottom: spacing.xs,
                }
              ]}>
                Generated Hash:
              </Text>
              <Text
                style={[
                  {
                    color: theme.colors.text,
                    ...typography.body,
                    fontFamily: 'monospace',
                  }
                ]}
                selectable
              >
                {generatedHash}
              </Text>
              <Text style={[
                {
                  color: theme.colors.textSecondary,
                  ...typography.caption,
                  marginTop: spacing.xs,
                  fontSize: 11,
                }
              ]}>
                Copy this hash and paste it into Firestore for the user's password field.
              </Text>
            </View>
          )}
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  header: {
    borderBottomWidth: 1,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center'
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1
  },
  title: {
    fontWeight: 'bold'
  },
  subtitle: {
    // Typography handled via theme
  },
  content: {
    // Padding handled inline
  },
  infoCard: {
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2
  },
  infoTitle: {
    fontWeight: 'bold'
  },
  infoText: {
    // Typography handled via theme
  },
  warningCard: {
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2
  },
  warningTitle: {
    fontWeight: 'bold'
  },
  warningText: {
    // Typography handled via theme
  },
  resultCard: {
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2
  },
  resultText: {
    // Typography handled via theme
  },
  seedButton: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5
  },
  seedButtonText: {
    fontWeight: 'bold'
  }
});

export default SeedDatabaseScreen;

